---
title: Cultural Division Component Library
timezone: UTC
collections:
  components:
    title: Components
    output: true
    permalink: "/:path/"
  developers:
    title: Developers
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  templates:
    title: Templates
    output: true
    permalink: "/:path/"
  uploads:
    title: Uploads
    output: true
email: mttwhlly@icloud.com
description: "A Component Library for Broward Cultural Division Website \n"
baseurl: 
url: "/"
permalink: "/:categories/:title/"
city: Broward Arts
markdown: kramdown
